[theme]
base = "light"
primaryColor = "#2346B8"
backgroundColor = "#EEF1F0"
secondaryBackgroundColor = "#E4E9E7"
textColor = "#15201C"

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
